version: "3"
services:

  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reminder
      - POSTGRES_USER=reminder
      - POSTGRES_PASSWORD=reminder
    volumes:
      - ./docker/postgres:/data

  django: &reminder_container
    build: .
    container_name: reminder-app-dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"

  worker:
    <<: *reminder_container
    ports: []
    command: python manage.py run_scheduled_tasks
    container_name: reminder-worker-dev
