version: "3"
services:

  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reminder
      - POSTGRES_USER=reminder
      - POSTGRES_PASSWORD=reminder
    volumes:
      - ./docker/postgres:/data

#    django: &reminder_container
  django:
    build: .
    container_name: reminder-app-dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - postgres

#    worker:
#      <<: *reminder_container
#      ports: []
#      command: python manage.py rqworker $WORKER_QUEUES
#      container_name: reminder-worker-dev
