# Generated by Django 3.1.4 on 2020-12-08 21:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from reminder.apps.events.models import EventStatus, UserRole


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "pub_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="If checked, this object is active. Uncheck to soft delete this object but"
                        " not any child or related objects.",
                        verbose_name="active",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("place", models.CharField(max_length=128)),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=EventStatus.choices, default="OPEN", max_length=32
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("role", models.CharField(choices=UserRole.choices, max_length=32)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "event")},},
        ),
    ]
